services:
  podcastify:
    build:
      context: .
      dockerfile: docker/podcastify/Dockerfile

    restart: unless-stopped

    ports:
      - "${HOST_PORT:-8080}:${SERVICE_PORT:-8080}"

    environment:
      - SERVICE_PORT=${SERVICE_PORT:-8080}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:-http://localhost:${HOST_PORT:-8080}}
      - PODCASTS_ROOT=${PODCASTS_ROOT:-/app/podcasts}
      - PUBLIC_ROOT=${PUBLIC_ROOT:-/app/public}
      - RUN_ON_START=${RUN_ON_START:-true}
      - PUBLISH_XML=${PUBLISH_XML:-true}

    volumes:
      - ./public:/app/public:rw
      - ./podcasts:/app/podcasts:rw
