name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
      - uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: meta
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/podcastify/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: true
          tags: |
            yourname/podcastify:latest
            yourname/podcastify:${{ steps.meta.outputs.VERSION }}
          labels: |
            org.opencontainers.image.title=PodCastify
            org.opencontainers.image.description=Create private podcast feeds from your own MP3s with zero fuss.
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.meta.outputs.VERSION }}
            org.opencontainers.image.authors=Aymen FNAYOU <fnayou.aymen@gmail.com>
